version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-asm}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-asm_pass}
      POSTGRES_DB: ${POSTGRES_DB:-asm_db}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - asmnet

  redis:
    image: redis:7
    networks:
      - asmnet

  api:
    build: ./backend
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
      - ./tools:/tools
    networks:
      - asmnet

  worker:
    build: ./backend
    command: ["celery", "-A", "app.workers.tasks.celery_app", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - ./backend/app:/app
      - ./tools:/tools
    networks:
      - asmnet

  frontend:
    build: ./frontend
    depends_on:
      - api
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/frontend
    networks:
      - asmnet

volumes:
  db_data:

networks:
  asmnet:
    driver: bridge
